name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: codeberg-small
    steps:
      - name: Create release
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          release-dir: .
          release-notes: "Release ${{ github.ref_name }}"
          token: ${{ secrets.FORGEJO_TOKEN }}

  build-linux:
    needs: create-release
    runs-on: codeberg-small
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: make VERSION=${GITHUB_REF_NAME}

      - name: Package binary
        run: |
          mkdir -p release
          cp chop release/chop-linux-amd64

      - name: Build .deb
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          mkdir -p chop_${VERSION}_amd64/usr/local/bin
          mkdir -p chop_${VERSION}_amd64/DEBIAN
          cp chop chop_${VERSION}_amd64/usr/local/bin/
          sed "s/\${VERSION}/${VERSION}/" debian/control > chop_${VERSION}_amd64/DEBIAN/control
          dpkg-deb --build chop_${VERSION}_amd64
          mv chop_${VERSION}_amd64.deb release/
          cd release && sha256sum * > checksums.txt

      - name: Upload to Debian registry
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          curl --fail --user "${{ secrets.PACKAGE_TOKEN }}" \
            --upload-file release/chop_${VERSION}_amd64.deb \
            https://codeberg.org/api/packages/mphillips/debian/pool/stable/main/upload

      - name: Upload assets
        run: |
          TAG=${GITHUB_REF_NAME}

          # Get release ID
          RELEASE_ID=$(curl -s \
            -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
            "https://codeberg.org/api/v1/repos/mphillips/chop/releases/tags/${TAG}" \
            | jq -r '.id')

          # Upload each file
          for file in release/*; do
            filename=$(basename "$file")
            curl --fail \
              -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
              -X POST \
              --upload-file "$file" \
              "https://codeberg.org/api/v1/repos/mphillips/chop/releases/${RELEASE_ID}/assets?name=${filename}"
          done

      - name: Trigger GitHub builds
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_DISPATCH_TOKEN }}" \
            https://api.github.com/repos/matthewp/chop/actions/workflows/release.yaml/dispatches \
            -d '{"ref":"main","inputs":{"version":"${{ github.ref_name }}"}}'
